# This file is a template, and might need editing before it works on your project.
# Official docker image.
image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

build-client-master:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/client" ./client
    - docker push "$CI_REGISTRY_IMAGE/client"
  only:
    - master

build-client:
  stage: build
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE/client:$CI_COMMIT_REF_SLUG" ./client
    - docker push "$CI_REGISTRY_IMAGE/client:$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags


build-server-master:
  stage: build
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE/server" ./server
    - docker push "$CI_REGISTRY_IMAGE/server"
  only:
    - master

build-server:
  stage: build
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG" ./server
    - docker push "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_REF_SLUG"
  except:
    - master
    - tags

build-client-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE/server:latest" --tag "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG" ./client
    - docker push "$CI_REGISTRY_IMAGE/server:latest"
    - docker push "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG"

build-server-tag:
  stage: build
  only:
    - tags
  script:
    - docker build --pull --tag "$CI_REGISTRY_IMAGE/server:latest" --tag "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG" ./server
    - docker push "$CI_REGISTRY_IMAGE/server:latest"
    - docker push "$CI_REGISTRY_IMAGE/server:$CI_COMMIT_TAG"

